In [18]:
import numpy as np

# import data
train_1 = np.loadtxt('./train1.txt')
train_2 = np.loadtxt('./train2.txt')
test = np.loadtxt('./test.txt')
train_1

array([[1.        , 0.        ],
       [0.7       , 0.3       ],
       [0.5347    , 0.49971   ],
       [0.43510691, 0.65248079],
       [0.37341678, 0.77763814],
       [0.33489347, 0.88561407],
       [0.31086856, 0.98275579],
       [0.29601842, 1.07306395]])

In [42]:
# make X, Y mats
x_mat = train_1[0:len(train_1) - 1, :]
y_mat = train_2[1:len(train_1), :]

# define psi transform
def psi_transform(x):
    transformed = np.zeros((x.shape[0], 10))
    if len(x.shape) == 1:
        
        transformed = np.zeros(10)

        transformed[0] = 1
        transformed[1] = x[0]
        transformed[2] = x[1]
        transformed[3] = x[0]**2
        transformed[4] = x[1]**2
        transformed[5] = x[0]*x[1]
        transformed[6] = x[0]**3
        transformed[7] = x[1]**3
        transformed[8] = x[1]*(x[0]**2)
        transformed[9] = (x[1]**2)*x[0]

    else:
        transformed = np.zeros((x.shape[0], 10))

        for i in range(x.shape[0]):
        
            transformed[i][0] = 1
            transformed[i][1] = x[i][0]
            transformed[i][2] = x[i][1]
            transformed[i][3] = x[i][0]**2
            transformed[i][4] = x[i][1]**2
            transformed[i][5] = x[i][0]*x[i][1]
            transformed[i][6] = x[i][0]**3
            transformed[i][7] = x[i][1]**3
            transformed[i][8] = x[i][1]*(x[i][0]**2)
            transformed[i][9] = (x[i][1]**2)*x[i][0]
            
    return transformed

In [43]:
psi_x = psi_transform(x_mat)
psi_y = psi_transform(y_mat)

In [44]:
psi_x_plus = np.linalg.inv(psi_x.T@psi_x)@psi_x.T

In [45]:
k = psi_y.T@psi_x_plus.T

In [46]:
c = np.zeros((10, 10))
c[0][1] = 1
c[1][2] = 1

In [47]:
test = psi_transform(train_1[0])

In [48]:
test

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 0.])

In [49]:
one_step = k@test

In [52]:
c@one_step

array([ 0.02432877, -0.06779797,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ])